### ISSUE TITLE
Ошибка. Не исчезает окошко поиска и замены.

### ISSUE THREAD

**Issue by lintest** [Pr-Mex/VAEditor#86]
Встроенный WebKit некорректно отрабатывает стиль CSS:
```CSS
.monaco-editor .find-widget {
  transform: translateY(calc(-100% - 10px));
}
```

![image](https://user-images.githubusercontent.com/92895/87254301-5a6f5c80-c48a-11ea-9d13-dc7a6b6cbe2d.png)
